### ISSUE TITLE
01:Not Working

### ISSUE THREAD

**Issue by ijnekenamay** [gerb-ster/Elka-Synthex-Curtis-VCF#1]
Hi!
I was so interested in this project that I actually fabricated and built a PCB!
But it doesn't work well, somewhere it shorts out and the power supply goes down.

I'm not sure if there was anything wrong with my build method. I am going to start debugging to see if there is a problem somewhere in the schematic.

Keep up the good work!

**Comment by gerb-ster** [comment]
Hi there,


Cool! Yeah, the status of that project is still ‘work in progress’.. I’ve build one myself a couple of weeks ago, and although I didn’t had any power issues, I didn’t get all the modes working properly. But then again, I didn’t thoroughly test I yet.

But it shouldn’t have any power issues; most commonly they are caused by either shorted caps/ic, bridged solder joints or op-amps put in the wrong way (I’ve lost quite a few op amp that wat :-)). But you should be able to buzz it out quite easily.

If you need any help, please let me know!


Greetings,

Gerb.

**Comment by ijnekenamay** [comment]
Thank you for responding!
Is there a specific fix you are aware of for the current PCB?

Thanks.
